### ISSUE TITLE
Creating a new tab with split view active, creates the new also split

### ISSUE THREAD

**Issue by LOTRg** [ddterm/gnome-shell-extension-ddterm#1002]
### GNOME Shell version

GNOME Shell 46.3.1

### Linux distro

"Fedora Linux 40 (Workstation Edition)"

### ddterm version

@amezin.github.com/bin/com.github.amezin.ddterm --version

ddterm 53 revision e21859c5431c36687018ba67c033060c00094be7
Extension 53 revision e21859c5431c36687018ba67c033060c00094be7

### Session type

X11

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### All installed extensions

```Text
ddterm@amezin.github.com
  Name: ddterm
  Description: Another drop down terminal extension for GNOME Shell. With tabs. Works on Wayland natively
  Path: /home/hb/.local/share/gnome-shell/extensions/ddterm@amezin.github.com
  URL: https://github.com/ddterm/gnome-shell-extension-ddterm
  Version: 53
  Enabled: Yes
  State: ACTIVE
```

### ddterm settings dump

```ini
[/]
background-opacity=0.90000000000000002
ddterm-activate-hotkey=@as []
ddterm-toggle-hotkey=['<Super>t']
detect-urls-news-man=false
new-tab-button=false
notebook-border=false
override-window-animation=false
palette=['rgb(81,81,81)', 'rgb(242,46,46)', 'rgb(78,154,6)', 'rgb(196,160,0)', 'rgb(52,101,164)', 'rgb(207,46,233)', 'rgb(19,191,194)', 'rgb(211,215,207)', 'rgb(126,122,122)', 'rgb(243,103,103)', 'rgb(138,226,52)', 'rgb(252,233,79)', 'rgb(114,159,207)', 'rgb(173,127,168)', 'rgb(109,251,251)', 'rgb(238,238,236)']
panel-icon-type='none'
preserve-working-directory=false
scrollback-unlimited=true
shortcut-split-horizontal=['<Alt>h']
shortcut-split-vertical=['<Alt>v']
shortcut-win-new-tab=['<Primary><Shift>t']
show-scrollbar=false
tab-close-buttons=false
tab-expand=false
tab-label-ellipsize-mode='none'
tab-policy='automatic'
tab-show-shortcuts=false
tab-switcher-popup=false
theme-variant='dark'
window-resizable=false
window-size=0.40000000000000002
```

### Description

When launching a window then splitting it either vertically or horizontally then starting a new tab, the new tab is NOT full window size, instead it's inheriting the size of the pane not the full size of the window. 

On a Vertical split, the new tab is the size of the active side and covers that pane only instead of being full size. Same happens on horizontal split.

**Comment by amezin** [comment]
Could you attach a screenshot please?

**Comment by amezin** [comment]
I do not see anything wrong on the screenshots.

And if I understand you correctly:

> When launching a window then splitting it either vertically or horizontally then starting a new tab, the new tab is NOT full window size, instead it's inheriting the size of the pane not the full size of the window.

this is also working as intended.

When you split the window, there are two panes, each has its own set of tabs.
