### ISSUE TITLE
Is it possible to use alternative terminals in ddterm?

### ISSUE THREAD

**Issue by rakaw** [ddterm/gnome-shell-extension-ddterm#102]
Hello, is it possible to use other terminals like kitty in ddterm as opposed to gnome-terminal? I've come across an issue with gnome-terminal not supporting images. For example, setting a custom neofetch image or running `w3m google.com` shows no images in gnome-terminal. There is the extension quake-mode, but the implementation into GNOME is different and it shows up on the overview screen, so it isn't as nice as ddterm.

Also, as far as I'm aware, setting default terminal in GNOME is not something you can do. 

Specs:
- Garuda Linux (Arch)
- Gnome 41.1
- ddterm: 24 (as of latest Fri Dec 3, 2021)

**Comment by amezin** [comment]
https://github.com/amezin/gnome-shell-extension-ddterm/discussions/95

ddterm is a terminal emulator itself, it's not using GNOME Terminal (although it shares a lot of code with GNOME Terminal, in the form of VTE library).

Quake-mode "isn't as nice" exactly because it tries to integrate with 3rd party terminal emulators

**Comment by rakaw** [comment]
> ddterm is a terminal emulator itself, it's not using GNOME Terminal

Thanks for replying. I see, that makes a lot of sense! And for quake-mode, i meant that it isn't as compatible with GNOME in terms of the workflow fluidity, not that it wasn't a nice project. 

Since ddterm is an actual terminal emulator, would it be possible to introduce image support for neofetch custom neofetch images and w3m? 
- `w3m google.com`
- `neofetch --source /path/to/img` or `neofetch --w3m /path/to/img`

**Comment by amezin** [comment]
I think my answer wasn't accurate.

ddterm and GNOME Terminal are "shells" for VTE, and VTE is the actual terminal emulator. The feature you're asking for should be implemented in VTE. So if it isn't working in GNOME Terminal - it won't work in ddterm too.

**Comment by rakaw** [comment]
Okay, thanks for your work!
