### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by vantu5z** [ddterm/gnome-shell-extension-ddterm#107]
Is it in plans to add localization support?

**Comment by amezin** [comment]
No, I didn't plan to add translations (if you mean that by "localization"). But most of the user-visible labels are in .ui files and even marked as "translatable." So, as far as I understand, it should be easily doable.

**Comment by amezin** [comment]
There is a French translation now https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/po/fr.po

**Comment by amezin** [comment]
I should probably connect the project to Transifex/Crowdin/some other translation tool.

@arnaud-feldmann What do you think? Do you have a preference?

**Comment by arnaud-feldmann** [comment]
Hi, I never used any of it, so I don't know.
That's your project, chose what you want :) As for me, i'd rather have a
simple thing that does its thing lets me do the manual .po edits without
overriding my choices, but your project your choice

Le mar. 19 juil. 2022, 07:50, Aleksandr Mezin ***@***.***> a
écrit :

**Comment by amezin** [comment]
@arnaud-feldmann I want some kind of web-based dashboard. Where I can see the statistics about untranslated messages. And where you could subscribe for notifications about new untranslated strings. Otherwise, it'll be hard to ensure that a new release is fully translated.

**Comment by amezin** [comment]
Also: source markers in *.po files (`#: glade/prefs.ui:36`) become outdated at some point. What's the typical approach to deal with them?

I see multiple options:
1. Require them to be always up to date in every commit (i. e. run msgmerge and fail if there is a diff).
2. Automatically update them periodically (daily/weekly)
3. Only update them when translation files are modified
4. Never update for existing messages

I'm leaning towards (1) - I like to keep everything up to date and correct. But it means that many commits will have to include translation file changes.

**Comment by arnaud-feldmann** [comment]
As you wish.

Thanks for you package anyway, that's very useful, simple, nicely
integrated into GNOME, and that's just what i needed.

Le mer. 27 juil. 2022, 20:15, Aleksandr Mezin ***@***.***> a
écrit :

**Comment by vantu5z** [comment]
Try to translate, but translation applied only for panel icon menu.
Should I do something else to apply it?

**Comment by arnaud-feldmann** [comment]
> Try to translate, but translation applied only for panel icon menu. Should I do something else to apply it?

@vantu5z What do you mean ? Have you tried to add a new translation, or to use my french one ?

**Comment by vantu5z** [comment]
@arnaud-feldmann I try to add Russian translation, what I do:
1. Create `ru.po` in `po/` dir.
2. run `make msgmerge` to add strings to *.po files.
3. edit po file by `gtranslator` (it add header string too).
4. run `make install` to compile translations and install addon.

All is fine, *.mo files is created, addon installed. But I see translation only in panel icon menu and not in prereference dialog or popup menu.

**Comment by amezin** [comment]
Dear translators, there are a few new strings: https://github.com/ddterm/gnome-shell-extension-ddterm/commit/8a5c56a05a2d4a486747f2e1bc1886f74971aff5

**Comment by arnaud-feldmann** [comment]
Ok I do that

**Comment by amezin** [comment]
I'll close this issue. Instead, I'll create new issues for new untranslated strings if/when they appear.
