### ISSUE TITLE
Allow changing tab bar separator colour

### ISSUE THREAD

**Issue by amankhoza** [ddterm/gnome-shell-extension-ddterm#1088]
![Screenshot From 2024-10-24 23-38-50](https://github.com/user-attachments/assets/8ca7f42e-7f40-4739-b4e8-594cca95cf72)
See attached screenshot, referring to the orange bar.

**Comment by amezin** [comment]
Do you mean just changing the color for all tabs (custom CSS styling?) or changing the color for an individual tab?

**Comment by amankhoza** [comment]
I just want to be able to change it for all tabs, don't need individual tab colours, could not see the option of changing this in the settings.

**Comment by amezin** [comment]
It's determined by Gtk (currently Gtk 3) theme

**Comment by amankhoza** [comment]
Ah I see, I have managed to change theme colours to customise this colour so closing this issue.
