### ISSUE TITLE
Compatibility issues with Material Shell

### ISSUE THREAD

**Issue by nikkolasg** [ddterm/gnome-shell-extension-ddterm#126]
Hi, 
I'm running latest Manjaro with Material Shell and I've just installed the extension but it is very slow, it takes <2s to show the terminal. I've removed the animations but still.
I'm wondering if this has anything to do with Material Shell, have you tried it with it ?
It's the only thing that I still miss from Material Shell.

Do you have any idea what could cause this ?

Thank you for the great project nevertheless !

**Comment by amezin** [comment]
Yes, it seems that there is a compatibility issue with Material Shell (apparently because both extensions try to move/resize the window).

I've been unable to resolve it by tweaking the settings.

**Comment by amezin** [comment]
Sorry, I completely forgot about this issue.

There was a similar issue in Material Shell repository: https://github.com/material-shell/material-shell/issues/40

And it seems that an appropriate configuration option was added: https://github.com/material-shell/material-shell/commit/15183774f2b393a32bdbbc69fc244f6e62d87bd9

You could add `com.github.amezin.ddterm` and `Com.github.amezin.ddterm` (on Xorg the first letter is capitalized, don't know why) to the exclude list.

Maybe I should submit a pull request adding ddterm there by default...

**Comment by amezin** [comment]
Hm. Re-tested Material Shell + ddterm on GNOME 43, and it seems that they don't conflict anymore, even without adding ddterm into exclude list. This may be different on other GNOME versions though.

Anyway, if some fix is needed - it should be done on Material Shell side - it should just ignore ddterm window.

**Comment by amezin** [comment]
There was a similar issue with another tiling extension: https://github.com/pop-os/shell/issues/1034 - they solved it by adding ddterm to the exclude list
