### ISSUE TITLE
Keyboard Shortcuts - Global/Application Shortcuts - Cannot detete/reset shortcuts, no reuse detection

### ISSUE THREAD

**Issue by aladar-mezga** [ddterm/gnome-shell-extension-ddterm#127]
Hi

There is no option to delete an associated shortcut, which can cause issues.
Also, there is no reuse detection so I can set the same shortcut for any number of actions.

![image](https://user-images.githubusercontent.com/98032467/166918767-c15e0c81-12de-4c9f-84da-0829de63793c.png)

Also I had issues finding the location of the configuration file to edit it manually which could have been a workaround and I found no related documentation about it either.

Is there a chance that these features will be implemented?

Thanks and best regards

Aladar

**Comment by vantu5z** [comment]
Also when set/unset keybinding - it will be shown/applied after config dialog is restarted. So you can't see if keybinding is set or not on a fly.

**Comment by amezin** [comment]
@vantu5z broken shortcut editor was a separate bug - fixed in https://github.com/ddterm/gnome-shell-extension-ddterm/pull/232 / https://github.com/ddterm/gnome-shell-extension-ddterm/releases/tag/v40
