### ISSUE TITLE
[feat] OSC 52 clipboard support

### ISSUE THREAD

**Issue by haoadoreorange** [ddterm/gnome-shell-extension-ddterm#130]
Hi, I know this is based on VTE but is it possible to patch it with support for OSC 52 escape sequence ? which is used for clipboard by tmux for example, it solves the ssh clipboard dilemma.

gnome-terminal doesn't support it due to security [concern](https://sunaku.github.io/tmux-yank-osc52.html).

**Comment by amezin** [comment]
ddterm uses VTE version that's installed in the system - so you only can patch it on your system.
Besides that, ddterm aims to mostly be a "GNOME Terminal clone, but attached to the screen edge".

Sorry that it took so long to respond.
