### ISSUE TITLE
[feature] Follow dark mode settings?

### ISSUE THREAD

**Issue by edgar-vincent** [ddterm/gnome-shell-extension-ddterm#131]
Hello,

Thank you very much for this beautiful extension, which is by far the best of its kind!
I run Gnome 42 with the [Night theme switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/) extension enabled, which, among other things, applies Gnome's new dark mode system-wide at night. `Console` seems to follow these global settings, and, for instance, its background color becomes dark at night. Would it be possible to get `ddterm` to have the same behaviour?

Thanks a lot,

EV

**Comment by amezin** [comment]
Is "Theme variant" set to "Dark" in preferences ("Colors" page)?

**Comment by edgar-vincent** [comment]
It is. See this screenshot:
![image](https://user-images.githubusercontent.com/63352906/179955483-b50fcee7-c5bf-4161-b4df-a8c932d6bab4.png)

The system theme is set to 'Dark' in the Gnome settings, and ddterm's theme variant is set to 'Default'. ddterm's background (at the top of the screen) is still white.

I seem to recall that Gnome's dark mode mechanism has been changed recently. Could it be related to this issue?

**Comment by edgar-vincent** [comment]
It works perfectly! Thanks a lot @amezin!

**Comment by rommeswi** [comment]
On Gnome 45 this does not seem to work anymore. In dark mode, terminal and ddterm have different color schemes.

**Comment by amezin** [comment]
Please open a new issue
