### ISSUE TITLE
Add compatibility for blur via blur-my-shell

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ddterm/gnome-shell-extension-ddterm#154]
https://github.com/aunetx/blur-my-shell#application-blurring
It works pretty nicely already via manual application blurring, but I believe manual integration could allow the blur part to be disabled (or animated, but I doubt this can be done) before the terminal prompt is fully shown. Furthermore, it would allow for the blur to be tied to the actual terminal prompt instead of the whole window (Which will allow to not got outside of it by also covering the title tabs and the window shadow).
[terminalblurshowcase.webm](https://user-images.githubusercontent.com/13170204/183070955-afcc513b-f7b6-4825-b35f-9965a211d202.webm)
[moreproeminentblurshowcase.webm](https://user-images.githubusercontent.com/13170204/183070985-ed630b18-2987-4263-a6e1-3ea776935541.webm)

**Comment by amezin** [comment]
From the videos it seems that blur-my-shell simply doesn't track window animations well (or at all). It seems to track only logical window coordinates, and ignores all transforms. This likely can and should be fixed in blur-my-shell itself.

On the other hand, built-in background blur could be a nice feature.

**Comment by MatthewScholefield** [comment]
Just wanted to mention that I tried it recently and it now seems to track the animation pretty much perfectly! :tada: (at least for me it does. I'm using wayland; not sure if that relates)

If anything, the only nice-to-have would maybe be a little info message next to the transparency in the settings with something like "Enable background blur via blur-my-shell. Learn more." with a link to a wiki page.
