### ISSUE TITLE
French translation: spaces before colons

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#159]
For example, https://github.com/ddterm/gnome-shell-extension-ddterm/blob/89a517ea021a797a54b44a2872f8bc5930c0e55c/po/fr.po#L165-L179

In English labels, there are no spaces before colons (which, according to my knowledge, is correct).
French translation - spaces before colons (which, as far as I know, is incorrect).

@arnaud-feldmann Could you fix it, please?

**Comment by arnaud-feldmann** [comment]
Hello, in french we put a space before the colons. That's one of the
differences. Same for "%" symbols

Le jeu. 11 août 2022, 19:14, Aleksandr Mezin ***@***.***> a
écrit :

**Comment by arnaud-feldmann** [comment]
Through stricto sensu it has to be an non breakable one, which I've not
done. I may do that at my return from vacations if you wish.

Le jeu. 11 août 2022, 20:44, Arnaud FELD ***@***.***> a
écrit :

**Comment by arnaud-feldmann** [comment]
https://leconjugueur.lefigaro.fr/frponctuationtypographie.php

**Comment by amezin** [comment]
Ok, sorry, did not expect punctuation rules to be that different. Yes, please replace these spaces with non-breakable ones.
