### ISSUE TITLE
Toggle Icon behaviour - rightclick?

### ISSUE THREAD

**Issue by sandreas** [ddterm/gnome-shell-extension-ddterm#181]
Hey,

thanks for `ddterm` - awesome tool. Would it be possible to change the default behaviour of the PanelIcon like this:

- `leftclick` is always toggle
- `rightclick` is always show popup menu

when toggle mode is enabled? Currently, rightclick does the same as leftclick and the preferences are no longer available, only over system settings...

What do you think?

**Comment by pesader** [comment]
Hey, I investigated a bit and got it working.

### Mouse behavior

Toggle if left or middle clicked, show menu if right clicked.

https://user-images.githubusercontent.com/65264536/216360000-0da2705f-9154-4622-82cf-432699f93f91.mp4

### Keyboard behavior

Always show menu.

https://user-images.githubusercontent.com/65264536/216360174-0c665dce-47f4-4bcb-8e76-3f6e2765dafd.mp4

**Comment by sandreas** [comment]
This is awesome... Thank you very much. Shall I close the issue?

**Comment by sandreas** [comment]
> Still, you can checkout my changes [here](https://github.com/pesader/gnome-shell-extension-ddterm/tree/panel-right-click) :)

Cool thx.

**Comment by Coburn** [comment]
I would like to see ddterm "show" simply by left-clicking the icon. Having to click the icon and then toggle the "show" switch is an extra step with no rationale, i.e. it doesn't give you any additional choices. Preferences should be a right-click. Thanks.

**Comment by amezin** [comment]
Implemented in https://github.com/ddterm/gnome-shell-extension-ddterm/pull/349, will be available in next release
