### ISSUE TITLE
Incompatible with Gnome 43

### ISSUE THREAD

**Issue by AkselMeola** [ddterm/gnome-shell-extension-ddterm#188]
Hey, 

Testing out fedora 37 beta with Gnome 43 beta.
All I can say is that extensions manager says the extension is no compatible with Gnome 43. 

`The extension is incompatible with the current GNOME version`
 
 Not sure how to see any debug output for extension manager to provide any additional info. Maybe it just need some version bump somewhere. 

---
Installed from gnome extensions website: https://extensions.gnome.org/extension/3780/ddterm/
 Claims to be version **36**

**Comment by gregorydk** [comment]
Adding 43 to `metadata.json` makes the extension work again.
