### ISSUE TITLE
Keeping the "Toggle Terminal Window" shortcut pressed freeze desktop on Gnome 42

### ISSUE THREAD

**Issue by Onion2222** [ddterm/gnome-shell-extension-ddterm#208]
Hello,

When I keep pressing the "switch to the terminal windows" shortcut (which is &), my computer completely freeze.
It happens when I press for more than 1sec.

Thanks for your amazing extension.
Arthur

**Comment by amezin** [comment]
There is no shortcut called like "switch to the terminal windows" in ddterm, at least in English UI.

If you have the UI in French, could you tell how exactly the shortcut is called (in French, not translating to English)? Is it "Basculer vers la fenêtre de terminal"?

Also, please specify your Linux distro and GNOME Shell version.

**Comment by amezin** [comment]
@arnaud-feldmann Google Translate translates "Basculer vers la fenêtre de terminal" as "Switch to terminal window". And now it seems that humans do the same too.

Are you sure "Basculer vers la fenêtre de terminal" is the best translation for "Toggle Terminal Window"?

**Comment by arnaud-feldmann** [comment]
@amezin Hum... I can't see a better translation right now. . It's a bit asymetrical that's true, because it means something like "toggle _**to**_", but you can't say basculer without the to. I'll try to check how it's translated in other packages

**Comment by arnaud-feldmann** [comment]
@amezin Honestly, the only other translation that I can find of toggle in that context is "Afficher/masquer", which is the exact translation of "Show/hide".

**Comment by amezin** [comment]
@Onion2222 Could you please tell your GNOME Shell version and Linux distro? Because I can't reproduce the problem on GNOME 43, Arch Linux.

Also, do you find the current shortcut name confusing, or is it perfectly clear?

**Comment by arnaud-feldmann** [comment]
@amezin 
If I install ddterm on my old thinkpad which has just had a fresh archlinux + gnome package, ddterm needs the package vte3, because gnome turned to gnome-console which has no dependencies on vte3.

That is, maybe, keeping toogle pushed would spam a lot of notifications "I can't find this lib", and then bug ?

Maybe you should warn people more about that dependency.

**Comment by amezin** [comment]
I've added that notification in the latest version, only about 24 hours ago. This bug was open before that.

**Comment by Onion2222** [comment]
> @Onion2222 Could you please tell your GNOME Shell version and Linux distro? Because I can't reproduce the problem on GNOME 43, Arch Linux.
> 
> Also, do you find the current shortcut name confusing, or is it perfectly clear?

Hello,
Thanks for your reply and sorry for the late, didn't have internet.
I'm using GNOME 42.4 on X11 with Ubuntu 22.04.1.

The shortcut name is very confusing.
![image](https://user-images.githubusercontent.com/62374537/201882622-08ec45cd-b124-4c21-b096-f3fc8c4d27ed.png)
It is the "Basculer vers la fenetre de terminal" shortcut which produce the issue when pressed a long time.
So for now I use "Afficher/activer la fenêtre de terminal" shortcut but I have to press the esc key to hide the terminal. (which is not a problem at all)

@arnaud-feldmann 
Effectivement le "vers" me pose problème, mais sans lui ce n'est plus très français.
Je pense que "Afficher/cacher la fenêtre de terminal" est plus claire (mais moins beau).

Tansks again for your help and for this great extension.

**Comment by amezin** [comment]
Should be fixed in v41

**Comment by Onion2222** [comment]
> Should be fixed in v41

Just tested and it works like a charm ! Thanks a lot !
[output.webm](https://user-images.githubusercontent.com/62374537/202098877-eded614f-5aac-4c63-b2dd-a672962bbd77.webm)
