### ISSUE TITLE
ddterm won't work / display

### ISSUE THREAD

**Issue by Jucgshu** [ddterm/gnome-shell-extension-ddterm#225]
Hi,

I've been joyfully using ddterm for a long time, and today I've decided to reinstall my Archlinux box. ddterm was working just fine before I reinstalled the box, and now only the prefs dialog box will appear. No more ddterm by itself, no matter what.

I've tried to launch it through the terminal using `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/ddterm --method com.github.amezin.ddterm.Extension.Toggle` or via the contextual menu with no luck. I've also tried to toy around with the prefs, including the X11 ones. Still not working.

Would someone have a clever idea on what I'm missing? I can't seem to find any logs nowhere.

GNOME 43.1.

Thanks for your help.

**Comment by Jucgshu** [comment]
Ok, so I tried to reinstall ddterm from cli with:
```
wget -NP /tmp/ddterm https://github.com/ddterm/gnome-shell-extension-ddterm/releases/latest/download/ddterm@amezin.github.com.shell-extension.zip
gnome-extensions install -f /tmp/ddterm/ddterm@amezin.github.com.shell-extension.zip
gnome-extensions enable ddterm@amezin.github.com
```
But still no luck :sob:

**Comment by amezin** [comment]
Could you look at `journalctl` output for errors?

Try to:
1. Open a terminal (some other app, not ddterm), start `journalctl --user -f` in it
2. Try to toggle ddterm using the hotkey

Ideally, you should do this after login/reboot (i. e. it should be the first attempt to activate ddterm).

You could also attach the output of `journalctl --user -b` here (collected after a failed attempt to activate ddterm).

**Comment by Jucgshu** [comment]
Good call. I had Vte4 installed where Vte3 was needed (actually `Vte-2.91.typelib`).

Thank you very much for your help @amezin, and thank you for your all your work on ddterm.

Closing the issue.
