### ISSUE TITLE
Enhancement: Padding

### ISSUE THREAD

**Issue by eshate** [ddterm/gnome-shell-extension-ddterm#242]
Firstly, of course - thank you for this terminal, great work!

One thing that I would request, should be quite easy. 
Is it possible to **customize the padding** of terminal input? 
It is so close to the borders right now, would be great to have some space for readability. 

Thanks!

**Comment by amezin** [comment]
ddterm just follows the default Gtk style... Is it different in GNOME Terminal/Console?

**Comment by eshate** [comment]
Thank you for that tip. Didn't know that. I never used GTerm and other natives longer than needed. As still exploring end-user I will try to ask proper question here. If we're talking about GTK, I've already had some fun in configs - but mostly theme additions, changing things like "highlight color" in PopShell (Pop's mod of Gnome). 

If I noticed well - whole GTK is adjustable by stylesheets. Does it mean that I should search for that config string, or make own config? Or should I check out how it behaves in GTerm and try to mimic it in Ddterm? 
What I'm trying to catch here is what do you mean by "follows default". Default GTK for terminal or some kind of default legacy settings? 

Sorry for noobing here, but some stuff still not obvious for me. Cannot really search it properly by keywords, so if you could throw me sth it'd be great.

**Comment by eshate** [comment]
Well, indeed!  As @amezin explained - **changing padding in GTK 3.0 stylesheet will affect also ddterm**. If anybody wants to know more, you can check this topic, for example - there are plenty of tutorials about padding in gterm. 

**Thanks, I'm closing this!**
