### ISSUE TITLE
fr.po: untranslated messages

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#283]
On the current `master` branch (3cabb28195eb96c1810ee1644f85ba81db85bbeb):

```
$ msgcmp  po/fr.po tmp/ddterm@amezin.github.com.pot
po/fr.po:22: this message is untranslated
po/fr.po:26: this message is untranslated
po/fr.po:30: this message is untranslated
po/fr.po:34: this message is untranslated
po/fr.po:38: this message is untranslated
```

I've added a "missing dependencies" notification. You can try it by running:

```
$ ./dependencies-notification.js --package test-package --file test-file
```

Also, ddterm now shows a warning when you need to restart GNOME Shell after update.

@arnaud-feldmann

**Comment by arnaud-feldmann** [comment]
PR #285 contains the requested updates. The dependencies notification has been tried :
![image](https://user-images.githubusercontent.com/60670870/208765363-fca84741-5a01-4fd0-b51c-8afbaba2d795.png)
