### ISSUE TITLE
ru.po: untranslated messages

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#284]
On the current `master` branch (3cabb28195eb96c1810ee1644f85ba81db85bbeb):

```
$ msgcmp  po/ru.po tmp/ddterm@amezin.github.com.pot
po/ru.po:24: this message is untranslated
po/ru.po:28: this message is untranslated
po/ru.po:32: this message is untranslated
po/ru.po:36: this message is untranslated
po/ru.po:40: this message is untranslated
```

I've added a "missing dependencies" notification. You can try it by running:

```
$ ./dependencies-notification.js --package test-package --file test-file
```

Also, ddterm now shows a warning when you need to restart GNOME Shell after update.

@vantu5z

**Comment by vantu5z** [comment]
Add PR #287 to update translations.

About restarting Gnome-Shell (re-login), should this enough:
1. Type `exit` in ddterm.
2. `Alt+F2` then `r` then `Return` to restart Gnome-shell.

I use only the first `exit` command to apply translations after do `make install` ddterm. But for now I get the warning about restarting Gnome that disappear after `Alt+F2 -> r` (without re-login).
From other side, when I try only `Alt+F2 -> r` to reload ddterm it does not work for me (before).

@amezin

**Comment by amezin** [comment]
`Alt+F2 -> r` works only in Xorg session. GNOME Shell on Wayland refuses to restart this way.

The warning appears when the version of the currently running application instance does not match the version of the currently loaded Shell extension. Because the version mismatch could cause various bugs, especially when extension's D-Bus interface changes (and this will happen in the next release).

> From other side, when I try only Alt+F2 -> r to reload ddterm it does not work for me (before).

Old application version is probably still running after Alt+F2 -> r.

In previous releases, the extension didn't kill the application on `disable()` on GNOME 42 and 43 - https://github.com/ddterm/gnome-shell-extension-ddterm/commit/0f6f13f240d867a0803b8bf6430d0f2ff55b9921

Do you still observe this behavior with the latest ddterm version?

**Comment by vantu5z** [comment]
Thanks for explanation!
> Do you still observe this behavior with the latest ddterm version?

Now it works fine.
