### ISSUE TITLE
D-Bus Activation

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#304]
Even when ddterm extension is active and installed, ddterm app might not be running (the app shuts down after the last tab is closed). But most D-Bus calls should end up in the application process. `com.github.amezin.ddterm` bus name is owned by the application process too.

D-Bus has an "activation" feaure - D-Bus daemon can automatically launch processes when a call is made to a specific name. 

However, ddterm app should be started only from the extension, especially on Wayland - otherwise some features won't work. [`com.github.amezin.ddterm`](https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/com.github.amezin.ddterm) script shouldn't be called directly. Instead, a D-Bus call to the extension should be performed - similar to the [`.desktop` file](https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/ddterm/com.github.amezin.ddterm.desktop#L7)

The extension should install a D-Bus service description file, similar to the `.desktop` file.

This will allow adding D-Bus features/interfaces to the application, without the need to "proxy" them through the extension, and the users won't have to worry whether the app is actually running. [GJS application packaging spec](https://gjs.guide/guides/gtk/application-packaging.html#index) also suggests applications should be D-Bus activatable.

**Comment by amezin** [comment]
https://dbus.freedesktop.org/doc/dbus-daemon.1.html

If the docs are correct, `$XDG_RUNTIME_DIR/dbus-1/services` is among the directories where D-Bus daemon looks for service files. `$XDG_RUNTIME_DIR` on my machine resolves to `/run/user/1000`. I think it is the most appropriate place for ddterm's service file, since it's generated at runtime, and doesn't need to be stored persistently.

Hm, maybe there's a similar subdir in `$XDG_RUNTIME_DIR` for desktop files...

**Comment by pesader** [comment]
Hi again! I could contribute making the `DesktopFile` class more generic (`InstallableResource` perhaps) so we can use the same code for installing the dbus service file.

We would only need to initialize each `InstallableResource` object with different values for `source_file` and `target_file`.

What do you think?

**Comment by pesader** [comment]
Now on the content of the service file itself, I found an example by GSConnect:

```
[D-BUS Service]
Name=org.gnome.Shell.Extensions.GSConnect
Exec=@PACKAGE_DATADIR@/service/daemon.js
```

So, when issue #315 is solved, I assume we can do something similar by calling the [com.github.amezin.ddterm](https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/com.github.amezin.ddterm) script.

**Comment by amezin** [comment]
You do not have to wait for #315 - you can just do the same `gdbus` call like in the `.desktop` file. #315 - right now I'm not sure if I should do it.

**Comment by amezin** [comment]
> Hi again! I could contribute making the `DesktopFile` class more generic (`InstallableResource` perhaps) so we can use the same code for installing the dbus service file.
> 
> We would only need to initialize each `InstallableResource` object with different values for `source_file` and `target_file`.
> 
> What do you think?

Yep, seems reasonable

**Comment by pesader** [comment]
> You do not have to wait for https://github.com/ddterm/gnome-shell-extension-ddterm/issues/315 - you can just do the same `gdbus` call like in the `.desktop` file.

Nice. So it would look something like this:

```yaml
[D-BUS Service]
Name=org.gnome.Shell.Extensions.ddterm
Exec=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/ddterm --method com.github.amezin.ddterm.Extension.Activate
```
