### ISSUE TITLE
CI: run linter last

### ISSUE THREAD

**Issue by pesader** [ddterm/gnome-shell-extension-ddterm#322]
When working on issue #297 and now #304 I often found myself making small changes without giving much thought to formatting and forgetting to run `make lint` before pushing to GitHub. I would then fix the formatting only to fail the actual tests and having to edit the code I just formatted.

Would you consider leaving the linter as the last step of the CI?

If you agree, I can make a PR for that as well.

**Comment by amezin** [comment]
No, linting is much faster than tests, so it must run first.

These tests are, unfortunately, not 100% stable. So, I'm repeating again: one or two failed tests may be fine, it's happening on master branch sometimes too. Ignore these failures if there are only 1 or 2 of them.

**Comment by pesader** [comment]
Would it be possible then to run the tests even if the linter fails?

```yaml
  test:
    needs:
    - lint # removing this
    - pack
    - configure-test-matrix
```

The CI would still fail, but at least the tests wouldn't be blocked by linter failures.

**Comment by amezin** [comment]
> But I get your point, if it is important the CI "fails fast" my proposal doesn't make sense.

Yes, it should fail fast, it's intentional.

If you want, you can run tests locally - see `test/README.md`.

**Comment by pesader** [comment]
> If you want, you can run tests locally - see test/README.md.

I didn't know that, thanks a lot!
