### ISSUE TITLE
Weblate for translations

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#365]
I decided to try Weblate https://hosted.weblate.org/projects/gnome-shell-extension-ddterm/ for translation.

Already found @vantu5z there and added to the project team.
@arnaud-feldmann do you have an account on https://hosted.weblate.org/ ?

**Comment by arnaud-feldmann** [comment]
I've just registered @amezin

**Comment by arnaud-feldmann** [comment]
I don't think it's very intuitive throught, I can't figure the changes I do to the project, I can't git diff, etc.
As for me, if it's possible, I'd rather keep on doing it the poedit way, is it possible ?

**Comment by amezin** [comment]
> As for me, if it's possible, I'd rather keep on doing it the poedit/git way, is it possible ?

Yes, should be possible.
