### ISSUE TITLE
Slow to open after closing

### ISSUE THREAD

**Issue by IvoryJam** [ddterm/gnome-shell-extension-ddterm#378]
### GNOME Shell version

GNOME Shell 43.3

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

gnome-extensions info ddterm@amezin.github.com | grep -Po 'Version:\s*\K\S+'

### Linux distro

Fedora Linux 37 (Workstation Edition)

### ddterm settings dump

background-color='rgb(23,20,33)'
ddterm-toggle-hotkey=['<Control>grave']
foreground-color='rgb(208,207,204)'
hide-when-focus-lost=true
hide-window-on-esc=true
notebook-border=false
override-window-animation=true
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
panel-icon-type='none'
show-scrollbar=false
tab-policy='automatic'
theme-variant='dark'
use-theme-colors=true
window-maximize=false
window-resizable=false

### Description

There's a noticeable time difference when starting ddterm the first time or after `exit` or `ctrl+d` is ran vs an already terminal. 

If I had to guess, I would say it takes 1.5s to start from cold or after close, about 0.5s after it's running.

**Comment by amezin** [comment]
Yes, because loading and starting the application (obviously) takes some time.

Is it much slower than GNOME Terminal?

**Comment by IvoryJam** [comment]
Which makes complete sense, I guess I was just hoping for the speed of like yakuake or something where the difference from cold start to re-opening is near non-existent.

**Comment by amezin** [comment]
If I'm not mistaken, yakuake auto-starts on login and runs in the background, because the app itself handles the hotkey.

With ddterm, only the shell extension loads on login. The actual application starts when you try to open it (and terminates when you close the last tab).

It should be possible to add a "keep running in background after all tabs were closed" option. But it should be a feature request, not a bug report :)

**Comment by amezin** [comment]
0.5s delay when the app is already running sounds suspicious though. Could you try to disable animations and try again? Default animation duration is 0.15s.

**Comment by IvoryJam** [comment]
If I drop those animations to 0s it still shows but is a lot faster, since it's not a widespread issue it my by system specific to me. I'll try it another a system to verify.

As for the "keep running in background" idea, I'll open a feature request for that.

**Comment by amezin** [comment]
> If I drop those animations to 0s

At least in the current `master` branch, there is a bug https://github.com/ddterm/gnome-shell-extension-ddterm/issues/380 - setting animation duration to `0` doesn't work. To disable animation you have to select "Disabled" in "Show/hide animation:" combo boxes.
