### ISSUE TITLE
Same shortcut to open / hide

### ISSUE THREAD

**Issue by wiiznokes** [ddterm/gnome-shell-extension-ddterm#386]
It would be convenient to have the option of assigning the same shortcut to both `ddterm-activate-hotkey `and `shortcut-window-hide`. If the terminal is already open, close it, else open it.

Btw, thanks for this great extension!

**Comment by amezin** [comment]
Maybe I misunderstand something...

Doesn't "Toggle Terminal Window"/`ddterm-toggle-hotkey` already do what you're asking for?

**Comment by wiiznokes** [comment]
Yes it does 😅 tks
