### ISSUE TITLE
wish to have a Gnome-shell 44 integration under wayland.

### ISSUE THREAD

**Issue by failafail8** [ddterm/gnome-shell-extension-ddterm#388]
you made the only gnome wayland terminal available
and it is a great one.
I wish to see it working under the gnome-shell 44 when you have time for it.

**Comment by amezin** [comment]
Current `master` branch supports GNOME 44. You can build and install the extension from source https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/docs/BUILD.md
