### ISSUE TITLE
ddterm window "flies over" from monitor with mouse to selected monitor

### ISSUE THREAD

**Issue by briaguya-ai** [ddterm/gnome-shell-extension-ddterm#405]
### GNOME Shell version

GNOME Shell 43.4

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [X] More than one monitor

### ddterm version

43

### Linux distro

"Debian GNU/Linux 12 (bookworm)" (debian sid)

### ddterm settings dump

```
[/]
ddterm-toggle-hotkey=['<Control>space']
override-window-animation=true
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
shortcuts-enabled=true
show-animation='linear'
window-monitor='connector'
window-monitor-connector='DP-1'
window-position='top'
```

#### Reproduction steps
* Have 2 monitors
* Select "On monitor" in the "Position and Size" tab in preferences
* Ensure mouse focus is on the monitor that is **not** selected
* Use keyboard shortcut or panel icon to toggle ddterm

#### Observed behavior
The terminal begins to display on the monitor with mouse focus before "flying over" to the selected monitor

#### Expected behavior
The terminal does not appear on the non-selected monitor at all

**Comment by amezin** [comment]
Yes, known issue.

1) ddterm "fights" with the window manager's placement logic
2) On Wayland, window properties arrive asynchronously, with a delay - so the extension can't immediately figure out which window is the correct one -> tries to move it too late

Hm, maybe if I change window detection to rely on window title instead of Gtk's D-Bus properties, it may improve this...

**Comment by amezin** [comment]
`master` branch contains a fix that should solve the problem for most of the cases. The fix will be included in v55 and later
