### ISSUE TITLE
Gnome 44 Release

### ISSUE THREAD

**Issue by woldtwerk** [ddterm/gnome-shell-extension-ddterm#430]
Hi,
when will the gnome 44 version be released?
Spotted gnome 44 support in the metadata.json already. Is there more work to be done?

**Comment by amezin** [comment]
Blocked by this https://github.com/ddterm/gnome-shell-extension-ddterm/issues/389

It's working, but the code isn't ready for review (and the release on extensions.gnome.org has to pass the review to be published).

**Comment by IamGeoffrey** [comment]
@amezin Thx for this, would it be possible to provide a build? 
I know there are build guides, but the .zip file would be awsome.

Thx for this amazing extension btw.

**Comment by amezin** [comment]
https://nightly.link/ddterm/gnome-shell-extension-ddterm/workflows/push/master/pack.zip?status=completed

Because of GitHub limitations, it's a `.zip` within `.zip`.

**Comment by divsmart** [comment]
I'm not a programmer, but ddterm is the best. I just downgraded back to Silverblue 37, just so I could keep using ddterm. It's that central to my workflow. I particularly like the ability to drag the window size.

**Comment by hailwood** [comment]
@amezin so with #389 closed now, where are we at with this release? :)

**Comment by divsmart** [comment]
> Blocked by this #389
> 
> It's working, but the code isn't ready for review (and the release on extensions.gnome.org has to pass the review to be published).

Thank you. I have been bugging you a bit lately on the extension site, but  I have dropped back to Silverblue 37, so take your time putting the finishing touches on it. ddterm is too good to rush.

**Comment by amezin** [comment]
> @amezin so with #389 closed now, where are we at with this release? :)

Now the recently added D-Bus activation doesn't work well https://github.com/ddterm/gnome-shell-extension-ddterm/issues/433

**Comment by hailwood** [comment]
> > @amezin so with #389 closed now, where are we at with this release? :)
> 
> Now the recently added D-Bus activation doesn't work well #433

Mate, you've got my respect.
This all sounds like a such a headache!

Thank you for your work on this.

**Comment by kkulebaev** [comment]
@amezin I see that #433 is closed. When will we have released ddterm for Gnome 44? :)

**Comment by EmixamPP** [comment]
Please stop spamming him with that question! It'll be ready when it's ready, period. 

I remind you that most open source projects are done in their spare time.
Putting pressure on them is absolutely no way of thanking them for their work.

**Comment by bigerl** [comment]
For some reason I had trouble with the package provided above. I've just rebuilt it from the latest [commit on main](https://github.com/ddterm/gnome-shell-extension-ddterm/commit/69b6f1d7e4b0600b3b6011839c2783c9a887726f). 
[ddterm@amezin.github.com.shell-extension.zip.zip](https://github.com/ddterm/gnome-shell-extension-ddterm/files/11830182/ddterm%40amezin.github.com.shell-extension.zip.zip)

Install with: 
```
unzip ddterm@amezin.github.com.shell-extension.zip.zip
gnome-extensions install -f ddterm@amezin.github.com.shell-extension.zip
```

Restart gnome afterwards. You'll find [here](https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md#3-restart-gnome-shell) how that works. If you feel too lazy to read it: just restart your machine.

**Comment by Somnius** [comment]
alt+f2 + r + enter doesn't work when wayland is running on a system, so just restart ;)
