### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#593]
@ddterm/translators 

There are missing strings, in every translation. If you plan to fix this, please do it soon - because the next release will likely be the last one supporting GNOME 44 and earlier. After that, users on GNOME 44 and earlier won't receive any updates, including translations.

**Comment by amezin** [comment]
@arnaud-feldmann There are also unreviewed suggestions for the French translation on Weblate

**Comment by amezin** [comment]
@arnaud-feldmann There are still 2 suggestions not reviewed. Please either accept or reject them.

**Comment by amezin** [comment]
@lcdessantos You're the main contributor to Portugese translation. Are you interested in maintaining it? I've just sent you invitations on both GitHub and Weblate

**Comment by amezin** [comment]
@novak-pavel You seem to be the only contributor to Czech translation. I've already sent you invitations, but you've ignored them. Are you interested in maintaining the translation, or are you giving it up?

**Comment by amezin** [comment]
@yuhldr You seem to be the only contributor to Chinese translation. I've already sent you invitations, but you've ignored them. Are you interested in maintaining the translation?

**Comment by novak-pavel** [comment]
Hi, I didn’t notice the invitations. I’ll try to maintain it.

ne 22. 10. 2023 v 15:08 odesílatel Aleksandr Mezin ***@***.***>
napsal:

**Comment by amezin** [comment]
@novak-pavel Ok, I've re-sent you the invitations, to both GitHub org and Weblate

**Comment by amezin** [comment]
@rizitis Do you plan to complete Greek translation?

**Comment by amezin** [comment]
@gnu-ewm Do you plan to complete Polish translation?

**Comment by rizitis** [comment]
I dont know how to translate the rest in Greek. The safe choice imo if someone else dont translate them is to stay in English...

**Comment by comradekingu** [comment]
@amezin https://github.com/ddterm/gnome-shell-extension-ddterm/issues/593#issuecomment-1774086727
Review isn't turned on for nb_NO, nor should it be.
Locking down translations on the assumption that person 2 doesn't have better ideas is a false assumption about who person 1 has to be.

I can't mark anything as needing review, and https://hosted.weblate.org/access/gnome-shell-extension-ddterm/#users isn't available to me.
Maybe I am not a reviewer, but then again that is a question of who can gauge whether I should be.
I am not able to do it for enough languages to manage anything. It mistakes verifiability for the ability to assign blame.

Opening up something to the gauntlet of potentially malicious people is still far better than discarding all changes that don't go through the "verified" chain of command.

If you turn on direct editing it is easy to make suggestions for source strings.
That way we can deal with the strings that aren't good.
Typically it will be the same strings for every translation, which can either be the ones not translated,  marked one way or the other, or translated last.

**Comment by gnu-ewm** [comment]
@amezin yes

**Comment by amezin** [comment]
@comradekingu I meant "Waiting for review" here

![image](https://github.com/ddterm/gnome-shell-extension-ddterm/assets/1273397/660770d1-e880-4134-9662-99b4b8b6fc78)

There are 13 strings in "Needs editing" state in Norwegian translation, they will be missing from UI - because it translates into "fuzzy" marker for gettext (and "Waiting for review" there is "ready, translated, not locked").

I'll look what can I do about source strings. Will Weblate edit `.pot` file in PRs if I enable direct editing?

**Comment by amezin** [comment]
And @comradekingu 

> Review isn't turned on for nb_NO, nor should it be.
> Locking down translations on the assumption that person 2 doesn't have better ideas is a false assumption about who person 1 has to be.

I don't insist on locking down (i. e. marking strings "approved"). If you want, you do it, if you don't want, you don't. It's up to the translator(s).

**Comment by amezin** [comment]
I've just noticed that "file:", "news:", "man:" URL scheme names were translated in some translations - while they shouldn't be. I didn't put them in quotes, so it's my mistake, at least partially.

I tried to correct this where it seemed obvious (in most translations) - but please double-check, maybe I used wrong quotes, for example.

@yuhldr I have no idea how to fix Chinese translation, you'll have to do it yourself.

Excuse me for the noise.

**Comment by amezin** [comment]
@rizitis 

> I dont know how to translate the rest in Greek. The safe choice imo if someone else dont translate them is to stay in English...

If the issue is that there's not enough context - you may try to use Weblate. It shows a corresponding screenshot for almost every string, and, sometimes, additional comments. Also, most of the UI duplicates GNOME Terminal - so looking at it could help too.

**Comment by amezin** [comment]
@comradekingu I've enabled https://docs.weblate.org/en/latest/workflows.html#source-reviews - it should allow reporting issues/suggestions for source strings

**Comment by amezin** [comment]
Thanks everyone, I've uploaded v47 to extensions.gnome.org. If everything goes well, it will be the last release for "old" GNOME versions. After it passes the review, I'll switch `master` branch to `gnome45`.

If somebody will complete another translation in few next days, it should be possible to upload another gnome 44 release (Polish, Portugese and Czech are close to completion, but still not 100%).

@novak-pavel @comradekingu Could you accept the invitation on Weblate, please?

**Comment by amezin** [comment]
Dear @ddterm/translators, please check your translations for missing/untranslated strings.

Currently, only Chinese translation is 100% complete.

I plan to release a new version with all fix/feature backports for GNOME 40-44, so it would be really nice to have complete translations too.
