### ISSUE TITLE
wl-copy/wl-paste 'hanging'

### ISSUE THREAD

**Issue by garfunkel** [ddterm/gnome-shell-extension-ddterm#622]
### GNOME Shell version

45.0

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

48

### Linux distro

Arch Linux

### ddterm settings dump

```ini
[/]
background-color='rgb(0,0,0)'
background-opacity=0.90000000000000002
bold-color-same-as-fg=true
bold-is-bright=true
cursor-colors-set=false
custom-font='Intel One Mono 16'
ddterm-toggle-hotkey=['F12']
force-x11-gdk-backend=false
foreground-color='rgb(0,255,0)'
hide-animation='linear'
hide-animation-duration=0.10000000000000001
highlight-colors-set=false
new-tab-button=true
notebook-border=false
override-window-animation=true
palette=['rgb(46,52,54)', 'rgb(204,0,0)', 'rgb(78,154,6)', 'rgb(196,160,0)', 'rgb(52,101,164)', 'rgb(117,80,123)', 'rgb(6,152,154)', 'rgb(211,215,207)', 'rgb(85,87,83)', 'rgb(239,41,41)', 'rgb(138,226,52)', 'rgb(252,233,79)', 'rgb(114,159,207)', 'rgb(173,127,168)', 'rgb(52,226,226)', 'rgb(238,238,236)']
scroll-on-output=false
scrollback-unlimited=true
shortcut-switch-to-tab-2=@as []
shortcut-win-new-tab=@as []
shortcut-win-new-tab-after-current=['<Primary><Shift>n']
shortcuts-enabled=true
show-animation='linear'
show-animation-duration=0.10000000000000001
show-scrollbar=true
tab-expand=true
tab-label-ellipsize-mode='end'
tab-label-width=0.10000000000000001
tab-policy='automatic'
tab-show-shortcuts=false
tab-switcher-popup=false
theme-variant='system'
transparent-background=true
use-system-font=false
use-theme-colors=false
window-maximize=false
window-monitor='current'
window-resizable=false
window-size=0.48999999999999999
```

### Description

This is kinda strange. In gnome-terminal and gnome-console, the Wayland clipboard tools (wl-copy and wl-paste) work as expected, but not in ddterm.

For example if I try:
`$ wl-copy CopyThisToTheClipboard`
it 'hangs' and never copies the text to the clipboard. Likewise:
`$ wl-paste`
does the same, and nothing is pasted.

**Comment by striczkof** [comment]
Literally same environment as above, also on Wayland Hi-DPI. Except, I'm just using a single monitor laptop.

I noticed that every time I attempt to copy/paste. this shows up in the journalctl:

```
Oct 28 17:54:35 alvins-xps9320 gnome-shell[150662]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**Comment by amezin** [comment]
It is a bug (or limitation) in wl-copy/wl-paste.

If you disable "Above All Windows" option in ddterm, wl-copy/wl-paste will work.

As far as I can tell, the issue is that these tools create a dummy window and expect that window to become active - which is obviously not happening if ddterm is in "Above All Windows" mode
