### ISSUE TITLE
ddterm not open

### ISSUE THREAD

**Issue by tony1016** [ddterm/gnome-shell-extension-ddterm#629]
### GNOME Shell version

GNOME Shell 44.3

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

Version: 47

### Linux distro

Alpine Linux 3.18

### ddterm settings dump

```ini
[/]
background-opacity=0.65000000000000002
ddterm-toggle-hotkey=['<Control>grave']
force-x11-gdk-backend=false
panel-icon-type='toggle-and-menu-button'
show-animation='disable'
show-animation-duration=0.10000000000000001
theme-variant='dark'
transparent-background=true
window-maximize=false
window-position='top'
window-resizable=false
window-size=0.78148854961832059
window-type-hint='normal'
```

### Description

Last version is ok.Fail to open after version update.

**Comment by amezin** [comment]
Bug report without any error messages doesn't help much.

Please do the following:

1. Log out
2. Login
3. Without pressing ddterm's hotkey/shortcut, open GNOME Terminal/Console
4. Start `journalctl -f` in GNOME Terminal/Console
5. Press ddterm's hotkey/shortcut
6. Copy `journalctl -f` output here

**Comment by tony1016** [comment]
Sorry but alpine linux doesn't use journalctl.I try to find logs but
there's none .

Aleksandr Mezin ***@***.***> 于2023年10月30日周一 01:33写道：

**Comment by amezin** [comment]
You'll have to figure out where GNOME Shell writes session logs on your system - otherwise I won't be able to help

**Comment by tony1016** [comment]
Ok, I will do that.

Aleksandr Mezin ***@***.***> 于2023年10月30日周一 10:30写道：

**Comment by amezin** [comment]
So the issue is likely that busybox's `realpath` doesn't understand `--`: https://github.com/ddterm/gnome-shell-extension-ddterm/pull/726

If still relevant, you should be able to fix this issue by editing `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm`: replace every `realpath --` with just `realpath` (there are two of them)

By the way, session logs are stored in `~/.cache/gdm/session.log`.

**Comment by tony1016** [comment]
> So the issue is likely that busybox's `realpath` doesn't understand `--`: #726
> 
> If still relevant, you should be able to fix this issue by editing `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm`: replace every `realpath --` with just `realpath` (there are two of them)
> 
> By the way, session logs are stored in `~/.cache/gdm/session.log`.

Yes confirm that
