### ISSUE TITLE
Improved Screen Splits

### ISSUE THREAD

**Issue by noahbliss** [ddterm/gnome-shell-extension-ddterm#644]
Hey! First off thanks for the traction on implementing this feature (https://github.com/ddterm/gnome-shell-extension-ddterm/issues/42). It's so close to being what I'm looking for to switch from guake. 

3 comments: 

1. There seems to be odd behavior (a bug) when trying to make a split on the first terminal instance. If I open a new tab, I can split as desired, but once I close all but the first tab, the option becomes grayed out. Any reason for this? 
2. Setting hotkeys that are typical terminal hotkeys (like ctrl+shift+e) do not seem to be respected by DD term and still retain their original function. 
3. Most other terminal emulators that support splitting (terminator, guake, iterm2, etc) allow recursive splits. The one I most commonly use is a vertical split, followed by a horizontal split on the right resulting in 3 terminals overall, a tall one on the left, and two squares on the right. It seems the current implementation only allows one split with a max of two terminals: either vertically split or horizontally split. Could this be investigated? 
4. I am asking for the moon here I know, but a hotkey to select the active "pane" based on direction (terminal left, terminal right, terminal up/down) would be great too. Mice are for cats, not Linux users. :P

**Comment by amezin** [comment]
Please don't mix multiple things together.

> There seems to be odd behavior (a bug) when trying to make a split on the first terminal instance. If I open a new tab, I can split as desired, but once I close all but the first tab, the option becomes grayed out. Any reason for this?

I can't reproduce the issue. If it happens, it's a bug, so please report it as a bug, with clear and detailed steps to reproduce.

> Setting hotkeys that are typical terminal hotkeys (like ctrl+shift+e) do not seem to be respected by DD term and still retain their original function.

Again, not enough details. For example, binding "Ctrl+Shift+E" to "Copy as HTML" action works for me. Please report as a bug, with clear and detailed steps to reproduce.

> Most other terminal emulators that support splitting (terminator, guake, iterm2, etc) allow recursive splits. The one I most commonly use is a vertical split, followed by a horizontal split on the right resulting in 3 terminals overall, a tall one on the left, and two squares on the right. It seems the current implementation only allows one split with a max of two terminals: either vertically split or horizontally split. Could this be investigated?

It's intentionally limited, for simplicity. Currently I have no plans on recursive splitting.

> I am asking for the moon here I know, but a hotkey to select the active "pane" based on direction (terminal left, terminal right, terminal up/down) would be great too.

Given the current limitations - one split - "Switch to other pane" should be enough https://github.com/ddterm/gnome-shell-extension-ddterm/issues/645
