### ISSUE TITLE
Add "Switch to Other Pane" action/keyboard shortcut

### ISSUE THREAD

**Issue by amezin** [ddterm/gnome-shell-extension-ddterm#645]
Somehow I forgot about it when implementing split layout.

Additional visual indication of the active pane would be nice too

**Comment by RafalSkolasinski** [comment]
Would be nice to have option to "switch to left pane" / "switch to right pane" - would be much more intuitive to add key bindings alt+left and alt+right - also it should not wraparound the panes.

Is it worth it to open a specific issue on this @amezin?

Bonus question (can open another issue) - was it considered to add multi-pane split? Right now I think one can only split the terminal once.

**Comment by amezin** [comment]
> Would be nice to have option to "switch to left pane" / "switch to right pane" - would be much more intuitive to add key bindings alt+left and alt+right - also it should not wraparound the panes.

> Is it worth it to open a specific issue on this @amezin?

Yes, it should be a separate feature request. However, I consider the current solution with one shortcut good enough, so I think I'm not going to work on it myself. But adding two shortcuts should be trivial.

> Bonus question (can open another issue) - was it considered to add multi-pane split? Right now I think one can only split the terminal once.

I'm not sure if I want this complexity it in the project. For me it looks like "no split" mode covers 90% cases, and two-pane mode covers additional 9%.
