### ISSUE TITLE
[Question] Width Setting - (maybe helpflul for wide screens)?

### ISSUE THREAD

**Issue by tobealive** [ddterm/gnome-shell-extension-ddterm#67]
Hello, i love to use the terminal! Thanks for the efforts!

Could you tell me if there is a way to set the width for the terminal? I'm using a wide screen and would like to have the terminal just in the center part.

Kind regards

**Comment by amezin** [comment]
No, currently, you can only change the height (well.. you can change the width if you set the terminal to the left/right position, but I guess it's not what you're asking for)

The main issue here is that configurable width adds more configurations to test. And some tests already run for ~20 min.

Also, I'm not sure how resizable window border(s) should work in this case.

Maybe I'll take a look at this again after I finish rewriting the test suite in python/pytest.

**Comment by amezin** [comment]
Duplicate of https://github.com/ddterm/gnome-shell-extension-ddterm/issues/129
