### ISSUE TITLE
Preserve the working directory or Show Tab bar on auitomactic. Does not work

### ISSUE THREAD

**Issue by ZennMystic** [ddterm/gnome-shell-extension-ddterm#683]
### GNOME Shell version

GNOME Shell 43.6

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

47

### Linux distro

"Debian GNU/Linux 12 (bookworm)"

### ddterm settings dump

```ini
[/]
command='user-shell'
custom-command=''
hide-when-focus-lost=true
hide-window-on-esc=true
new-tab-front-button=true
notebook-border=false
pointer-autohide=true
preserve-working-directory=true
tab-label-ellipsize-mode='start'
tab-policy='automatic'
tab-position='top'
window-maximize=true
window-monitor='primary'
window-position='top'
window-size=1.0
window-skip-taskbar=false
```

### Description

It does not preserve the working directory. Nor does Show Tab Bar work when set to automatic.

**Comment by amezin** [comment]
I can't reproduce any issues with the working directory or tab bar in Debian 12 VM.

> It does not preserve the working directory

For me, opening a new tab copies the working directory from the active tab - works as expected.

Please describe:
1. What you do
2. What happens
3. What you expected to happen

> Nor does Show Tab Bar work when set to automatic.

For me, the tab bar shows when I open more than one tab, and hides when there's only one tab - works as expected.

Please describe:
1. What you do
2. What happens
3. What you expected to happen

**Comment by ZennMystic** [comment]
After trying more I think I was not understanding exactly what ddterm is. I thought I would be able to use to open terminal in quick in whatever folder I was in and it know.
But I see now just a terminal that remember were you were on last use yes? Have it right now?

I embarrassment sorry. I would like to remove my report now.

the only issue I have now since update of is Clipboard provider: wl-paste+wl-copy
System clipboard provider: wl-paste+wl-copy

like if I use ddterm and lunch my editor from Helix. hx <file> then inside do a system clipboard copy. I get the clipboard icon up and have to click in it. it disappear right away but now has the thing I copied. where if I do not click on icon it will not have copy.
if I use normal terminal no issue no problem.
    On Thursday, November 30, 2023 at 03:48:13 PM CST, Aleksandr Mezin ***@***.***> wrote:  
 
 


I can't reproduce any issues with the working directory or tab bar in Debian 12 VM.


It does not preserve the working directory


For me, opening a new tab copies the working directory from the active tab - works as expected.

Please describe:
   
   - What you do
   - What happens
   - What you expected to happen


Nor does Show Tab Bar work when set to automatic.


For me, the tab bar shows when I open more than one tab, and hides when there's only one tab - works as expected.

Please describe:
   
   - What you do
   - What happens
   - What you expected to happen
