### ISSUE TITLE
dconf schemas missing describing the keys

### ISSUE THREAD

**Issue by LILNAZ** [ddterm/gnome-shell-extension-ddterm#698]
### GNOME Shell version

44.6 and 40.10

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### ddterm version

47 and 32

### Linux distro

Fedora 39 and Red Hat 9.2

### ddterm settings dump

```ini
[/]
background-color='#282A36'
background-opacity=0.80000000000000004
bold-color='#6E46A4'
bold-color-same-as-fg=false
bold-is-bright=false
cursor-background-color='#000000'
cursor-blink-mode='system'
cursor-colors-set=false
cursor-foreground-color='#ffffff'
cursor-shape='block'
foreground-color='#F8F8F2'
highlight-background-color='#000000'
highlight-colors-set=false
highlight-foreground-color='#ffffff'
override-window-animation=true
palette=['#262626', '#E356A7', '#42E66C', '#E4F34A', '#9B6BDF', '#E64747', '#75D7EC', '#EFA554', '#7A7A7A', '#FF79C6', '#50FA7B', '#F1FA8C', '#BD93F9', '#FF5555', '#8BE9FD', '#FFB86C']
panel-icon-type='toggle-and-menu-button'
scroll-on-output=true
scrollback-lines=10005
scrollback-unlimited=true
show-animation='linear'
show-animation-duration=0.14999999999999999
tab-label-ellipsize-mode='middle'
tab-label-width=0.10000000000000001
theme-variant='dark'
use-theme-colors=false
window-above=true
window-maximize=false
window-monitor='current'
window-position='top'
window-size=0.59999999999999998
window-stick=true
```

### Description

When I try to change the settings via gsettings or creating local.d settings (`/etc/dconf/db/local.d/`) files nothing happens or paths are non existent.

```
gsettings get com.github.amezin.ddterm bold-color
No such schema “com.github.amezin.ddterm”
```

If I look in dconf it states:
`No schema available. A schema is what describes the use of a key, and Dconf Editor can't find one associated with this key. If the application that was using this key has been uninstalled, or if this key is obsolete, you may want to erase it.`

I believe this the problem why gsettings cannot set the values.

However, this works:
```
dconf write /com/github/amezin/ddterm/scrollback-unlimited false
```

**Comment by amezin** [comment]
GNOME Shell extensions have schemas file(s) inside the extension installation directory, in `schemas` subdirectory.

There is `gsettings --schemadir ...` option and `GSETTINGS_SCHEMA_DIR` environment variable exactly for this case.

For system-wide installation (i. e. as a distro-specific package, or `sudo make install`) it's possible to install the schemas file into the default system-wide schemas directory (usually `/usr/share/glib-2.0/schemas`), but currently it's not performed.

After migration to meson build system https://github.com/ddterm/gnome-shell-extension-ddterm/issues/648 schemas will be installed into `/usr/share/glib-2.0/schemas` for system-wide installation.
