### ISSUE TITLE
Color palette overrides zsh theme

### ISSUE THREAD

**Issue by inhaledesign** [ddterm/gnome-shell-extension-ddterm#742]
### GNOME Shell version

45.0

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [ ] More than one monitor

### Extension version

49

### Linux distro

Ubuntu 23.10

### Verbose version information

ddterm 49 revision 73297878ac855f764e27fc2f31886c018419d34d
Extension 49 revision 73297878ac855f764e27fc2f31886c018419d34d

### ddterm settings dump

```ini
[/]
audible-bell=false
background-color='rgb(255,255,255)'
background-opacity=0.90000000000000002
cursor-blink-mode='on'
cursor-shape='underline'
ddterm-toggle-hotkey=['F1']
foreground-color='rgb(0,0,0)'
hide-animation='ease-out-sine'
hide-when-focus-lost=true
hide-window-on-esc=true
palette=['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']
pointer-autohide=true
show-animation='ease-in-sine'
show-animation-duration=0.14999999999999999
theme-variant='system'
use-system-font=true
use-theme-colors=true
window-maximize=false
window-size=0.48282442748091603
window-stick=true
```

### Description

I'm using zsh as my shell. I have a color theme  that gets loaded in my .zshrc file via zplug:

`zplug "dracula/zsh", as:theme`

This loads the theme fine in gnome-terminal and other terminal programs. However, in ddterm, the color of my theme is still determined by ddterm's Colors > Palette setting. It would be nice if there was an option to disable using the settings palette.

**Comment by amezin** [comment]
16-color palette is configurable, and 256-color one is not - it uses built-in VTE palette. Last time I checked, it was exactly like in GNOME Terminal.

https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh - shows both palettes.

**Comment by inhaledesign** [comment]
> 16-color palette is configurable, and 256-color one is not - it uses built-in VTE palette. Last time I checked, it was exactly like in GNOME Terminal.
> 
> https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh - shows both palettes.

My bad, I thought the 16 color palette was a system-wide setting.
