### ISSUE TITLE
Increase text size on the fly

### ISSUE THREAD

**Issue by jediaxe** [ddterm/gnome-shell-extension-ddterm#75]
I have noticed that none of the common keyboard shortcuts work to increase text size in ddterm.
Can this be added to Keyboard Shortcuts in ddterm settings?

In the meantime. can you please share the shell command that will increase/decrease text size within ddterm?

Update:
GNOME Shell 40.3
Wayland

**Comment by amezin** [comment]
> Can this be added to Keyboard Shortcuts in ddterm settings?

Yes, it's a small, easy-to-implement feature. https://gjs-docs.gnome.org/vte291~2.91_api/vte.terminal#property-font_scale

I'll accept a pull request that implements it. I do not have time to work on the feature myself though.

> can you please share the shell command that will increase/decrease text size within ddterm?

There is no such command (currently)

**Comment by jelical** [comment]
Also Ctrl+Scroll (chrome like) will be very welcome addition in this area

**Comment by amezin** [comment]
Will be available in the next release (there will still be one more for GNOME <45)

> Also Ctrl+Scroll (chrome like) will be very welcome addition in this area

Neither GNOME Terminal nor Console do this, so not sure if it's a good idea
