### ISSUE TITLE
Change window title(?) from 'com.github.amezin.ddterm' to 'ddterm' 

### ISSUE THREAD

**Issue by eode** [ddterm/gnome-shell-extension-ddterm#78]
This is a very minor cosmetic issue, but:

When the window is displayed, in the activity bar, where a window's title is normally displayed, DDTerm shows up as "com.github.amezin.ddterm".  It would be nice if this were just 'ddterm".

**Comment by pesader** [comment]
I think this can be closed as completed because of 7ee4db0 :)

**Comment by amezin** [comment]
@pesader Yes, thank you

Fixed in `master`/will be available in v44
