### ISSUE TITLE
export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by RafalSkolasinski** [ddterm/gnome-shell-extension-ddterm#787]
### GNOME Shell version

GNOME Shell 44.8

### Linux distro

Fedora Linux 38 (Workstation Edition)

### ddterm version

bash: com.github.amezin.ddterm: command not found...
ddterm 49 revision 73297878ac855f764e27fc2f31886c018419d34d
Extension undefined revision undefined
Warning: ddterm version has changed. Log out, then log in again to load the updated extension.

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [X] More than one monitor

### All installed extensions

appindicatorsupport@rgcjonas.gmail.com
  Name: AppIndicator and KStatusNotifierItem Support
  Description: Adds AppIndicator, KStatusNotifierItem and legacy Tray icons support to the Shell
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com
  URL: https://github.com/ubuntu/gnome-shell-extension-appindicator
  Version: 53
  State: ENABLED

unblank@sun.wxg@gmail.com
  Name: Unblank lock screen
  Description: Unblank lock screen.
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/unblank@sun.wxg@gmail.com
  URL: https://github.com/sunwxg/gnome-shell-extension-unblank
  Version: 29
  State: ENABLED

just-perfection-desktop@just-perfection
  Name: Just Perfection
  Description: Tweak Tool to Customize GNOME Shell, Change the Behavior and Disable UI Elements
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection
  URL: https://gitlab.gnome.org/jrahmatzadeh/just-perfection
  Version: 26
  State: INITIALIZED

quake-mode@repsac-by.github.com
  Name: quake-mode
  Description: Drop-down mode for any application
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/quake-mode@repsac-by.github.com
  URL: https://github.com/repsac-by/gnome-shell-extension-quake-mode
  Version: 9
  State: INITIALIZED

Always-Show-Titles-In-Overview@gmail.com
  Name: Always Show Titles In Overview
  Description: Customize Gnome 3 overview.

- Always show titles of all window thumbnails
- Always show close buttons of all window thumbnails
- Window titles position (Bottom, Center)
- Move window titles to the bottom when fullscreen
- Move window titles to the bottom for video/TV players, like SMPlayer
- Show/hide app icons
- App icon position: Bottom, Center
- Show/hide the app icon when a window is in fullscreen mode
- Show/hide the background
- Hide/show icons for Video/TV players, like SMPlayer
- Tweak the window thumbnail active size increment (from 5 to 60, the default is 15)
- Hide the background 

  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com
  URL: https://github.com/nlpsuge/Always-Show-Titles-In-Overview
  Version: 23
  State: ENABLED

cpupower@mko-sl.de
  Name: CPU Power Manager
  Description: Manage your CPU's frequency scaling driver
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/cpupower@mko-sl.de
  URL: https://github.com/deinstapel/cpupower
  State: INITIALIZED

window-state-manager@kishorv06.github.io
  Name: Window State Manager
  Description: Automatically remember and restore window state and positions. Useful when using Gnome with wayland in a multi-monitor setup. Some applications won't remember their location when monitors are connected or disconnected. This extension solves that problem by saving window state periodically and restoring it when screen arrangement is changed.
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/window-state-manager@kishorv06.github.io
  URL: https://github.com/kishorv06/window-state-manager
  Version: 4
  State: ENABLED

vertical-workspaces@G-dH.github.com
  Name: V-Shell (Vertical Workspaces)
  Description: Customize your GNOME Shell UX to suit your workflow, whether you like horizontally or vertically stacked workspaces.
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com
  URL: https://github.com/G-dH/vertical-workspaces
  Version: 53
  State: ENABLED

ddterm@amezin.github.com
  Name: ddterm
  Description: Another drop down terminal extension for GNOME Shell. With tabs. Works on Wayland natively
  Path: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com
  URL: https://github.com/ddterm/gnome-shell-extension-ddterm
  Version: 49
  State: ERROR

apps-menu@gnome-shell-extensions.gcampax.github.com
  Name: Applications Menu
  Description: Add a category-based menu for applications.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  State: INITIALIZED

background-logo@fedorahosted.org
  Name: Background Logo
  Description: Overlay a tasteful logo on the background to enhance the user experience
  Path: /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org
  URL: https://pagure.io/background-logo-extension
  State: ENABLED

launch-new-instance@gnome-shell-extensions.gcampax.github.com
  Name: Launch new instance
  Description: Always launch a new instance when clicking in the dash or the application view.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  State: INITIALIZED

places-menu@gnome-shell-extensions.gcampax.github.com
  Name: Places Status Indicator
  Description: Add a menu for quickly navigating places in the system.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  State: INITIALIZED

window-list@gnome-shell-extensions.gcampax.github.com
  Name: Window List
  Description: Display a window list at the bottom of the screen.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  State: INITIALIZED

user-theme@gnome-shell-extensions.gcampax.github.com
  Name: User Themes
  Description: Load shell themes from user directory.
  Path: /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  State: INITIALIZED

### ddterm settings dump

```ini
[/]
background-color='rgb(10,17,36)'
background-opacity=0.95999999999999996
foreground-color='rgb(237,194,154)'
hide-animation='linear'
hide-animation-duration=0.050000000000000003
notebook-border=true
override-window-animation=false
palette=['rgb(37,37,37)', 'rgb(255,82,82)', 'rgb(195,216,44)', 'rgb(255,193,53)', 'rgb(66,165,245)', 'rgb(216,27,96)', 'rgb(0,172,193)', 'rgb(245,245,245)', 'rgb(112,130,132)', 'rgb(255,82,82)', 'rgb(195,216,44)', 'rgb(255,193,53)', 'rgb(66,165,245)', 'rgb(216,27,96)', 'rgb(0,172,193)', 'rgb(245,245,245)']
shortcut-move-tab-to-other-pane=@as []
shortcut-set-custom-tab-title=['<Primary>m']
shortcut-split-horizontal=['<Primary><Alt>d']
shortcut-split-position-dec=['<Shift><Alt>Left']
shortcut-split-position-inc=['<Shift><Alt>Right']
shortcut-split-vertical=['<Primary><Alt>r']
shortcut-terminal-reset=@as []
shortcut-terminal-reset-and-clear=@as []
shortcuts-enabled=true
show-animation='linear'
show-animation-duration=0.050000000000000003
tab-expand=false
tab-label-ellipsize-mode='none'
tab-switcher-popup=true
use-theme-colors=false
window-maximize=false
window-monitor='primary'
window-monitor-connector='DP-3'
window-size=0.34999999999999998
```

### Description

Installing version 50 or 49 released on github leads to `export declarations may only appear at top level of a module`

```
Feb 09 14:58:28 vai gnome-shell[351387]:   inflating: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/locale/zh_CN/LC_MESSAGES/ddterm@amezin.github.com.mo
Feb 09 14:58:28 vai gnome-shell[351387]:   inflating: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/misc/extensionUtils.js
Feb 09 14:58:28 vai gnome-shell[351387]:   inflating: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/prefs.js
Feb 09 14:58:28 vai gnome-shell[351387]:  extracting: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/revision.txt
Feb 09 14:58:28 vai gnome-shell[351387]:   inflating: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/schemas/com.github.amezin.ddterm.gschema.xml
Feb 09 14:58:28 vai gnome-shell[351387]:   inflating: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/schemas/gschemas.compiled
Feb 09 14:58:28 vai gnome-shell[351387]:  extracting: /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/metadata.json
Feb 09 15:00:39 vai gnome-shell[353429]: JS ERROR: Extension ddterm@amezin.github.com: SyntaxError: export declarations may only appear at top level of a module @ /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:20:0
Feb 09 15:02:34 vai gnome-shell[356504]: JS ERROR: Extension ddterm@amezin.github.com: SyntaxError: export declarations may only appear at top level of a module @ /home/rskolasinski/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/extension.js:20:0
```

**Comment by amezin** [comment]
Yes, v49 and v50 support GNOME 45 only. The last release that supported GNOME 44 was v47.

And you seem to have extension compatibility checks turned off.

If for some reason you want the latest code on older GNOME, it's possible to build the current `master` branch targeting GNOME 41-44 with [`meson setup -Desm=false`](https://github.com/ddterm/gnome-shell-extension-ddterm/blob/master/meson_options.txt) but it's not well tested and not documented yet.

**Comment by RafalSkolasinski** [comment]
> Yes, v49 and v50 support GNOME 45 only. The last release that supported GNOME 44 was v47.

That would explain why it doesn't work :sweat_smile: 

> And you seem to have extension compatibility checks turned off.

Must have been from past experiments with other extensioons

> If for some reason you want the latest code on older GNOME, 

Nah, I will probably prioritize my fedora upgrade on this machine. I mainly tried to upgrade as addition of shortcut to switch between panes was something I found really missing.
