### ISSUE TITLE
Gnome 46 not working

### ISSUE THREAD

**Issue by stouracp** [ddterm/gnome-shell-extension-ddterm#838]
### GNOME Shell version

GNOME Shell 46.0

### Linux distro

"Fedora Linux 40 (Workstation Edition Prerelease)"

### ddterm version

bash: com.github.amezin.ddterm: Příkaz nebyl nalezen...
ddterm 51 revision 9977d80a619f4a1e499c5ae93ca2340a7082c615
Extension undefined revision undefined
Can't read the version of the loaded extension.
Please, make sure ddterm GNOME Shell extension is enabled.

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [X] High DPI
- [X] More than one monitor

### ddterm settings dump

```ini
background-color='rgb(23,20,33)'
custom-font='Monospace 14'
detect-urls-voip=false
foreground-color='rgb(208,207,204)'
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
scrollback-unlimited=true
tab-label-width=0.050000000000000003
theme-variant='dark'
use-system-font=false
use-theme-colors=false
window-maximize=false
window-size=0.89953703703703702
```

**Comment by stouracp** [comment]
error: TypeError: class heritage MessageTray.NotificationBanner is not an object or null

**Comment by amezin** [comment]
v51 doesn't mention GNOME 46 support anywhere https://github.com/ddterm/gnome-shell-extension-ddterm/releases/tag/v51

For GNOME 46, your only current option is `master` branch
