### ISSUE TITLE
Tabs get focus

### ISSUE THREAD

**Issue by lfom** [ddterm/gnome-shell-extension-ddterm#87]
Hello!

Thanks for ddterm, I have been using since a while ago and I really enjoy it. Thanks a lot for this useful extension!

Small glitch/bug: clicking on the tabs with the mouse a second time focus the tab switch label, so what is typed does not go to the terminal. What is even weirder is that if you do it when a new tab is created then I can see the dashed line showing the focus, but if I hide then show again the terminal it behaves the same way but the dashed line is gone. I have played with the .ui files trying to disable the focus but it did not work, maybe it is hard coded somewhere?

Regards

**Comment by amezin** [comment]
These are two separate issues. Could you report them as such? i. e. "New issue" and move one of the two paragraphs there.

**Comment by lfom** [comment]
Done, search glitch moved to #89.

**Comment by lfom** [comment]
Yes, GTK notebook is a little weird but I am sure this can be done. Both Gnome Terminal and Terminal use it for tabs and in both the tabs are not focuses and clicked, although you can still click (of couse) and double-click and secondary-click. Maybe setting the GTK property has_focus/can_focus in the code with prevent this?

**Comment by amezin** [comment]
Fix will be included in the next release
